spring:
  profiles:
    active:
    - prod
app:
  datasource:
    jdbc-url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    maximum-pool-size: 30
